<?php
/**
* @file
* Módulo para probar menus
* Este módulo crea un elemento de menú
*/

/**
 * Implements hook_menu().
 */
function menu_forcontu_menu() {
  $items['pagina1'] = array(
    'title' => 'Menu Forcontu',
    'page callback' => 'menu_forcontu_pagina1',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['calculadora/%/%'] = array(
    'title' => 'Calculadora',
    'page callback' => 'menu_forcontu_calculadora',
    'page arguments' => array(1, 2),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['calculadora/%'] = array(
    'title' => 'Calculadora',
    'page callback' => 'menu_forcontu_calculadora',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['calculadora'] = array(
    'title' => 'Calculadora',
    'page callback' => 'menu_forcontu_calculadora',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['admin/config/development/pagina1'] = array(
    'title' => 'Página 1',
    'page callback' => 'menu_forcontu_menu1',
    'description' => 'Menú página 1',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'weight' => -99,
  );
  //Actividad 46.4 Creación de pestañas
  $items['tabs'] = array(
    'title' => 'Pestañas',
    'page callback' => 'menu_forcontu_tab1',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
    'weight' => 1,
  );
  $items['tabs/tab1'] = array(
    'title' => 'Pestaña 1',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 1,
  );
  $items['tabs/tab2'] = array(
    'title' => 'Pestaña 2',
    'page callback' => 'menu_forcontu_tab2',
    'access callback' => 'user_access',
    'access arguments' => array('access to menu forcontu'),
    'type' => MENU_CALLBACK | MENU_LOCAL_TASK,
    'weight' => 2,
  );
  $items['tabs/tab3'] = array(
    'title' => 'Pestaña 3',
    'page callback' => 'menu_forcontu_tab3',
    'access callback' => TRUE,
    'type' => MENU_LOCAL_TASK,
    'weight' => 3,
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function menu_forcontu_permission() {
  return array(
    'access to menu forcontu' =>  array(
      'title' => t('Acces to menu Forcontu'),
      'description' => t('Allows access to restricted pages of 
the menu items defined in Menu Forcontu'),
    ),
  );
}

/**
* Page callback
* Función que se invocará al cargar la página www.example.com/pagina1
*/
function menu_forcontu_pagina1() {
  $output = t('Main page of the module Menu Forcontu');
  return $output;
}

/**
* Page callback
* Función que se invoca al cargas la página www.example.com/calculadora/%/%
*/
function menu_forcontu_calculadora($x=0, $y=0) {
  $output = '<p>La suma de ' . $x . ' y ' . $y . ' es: ' . ($x + $y) . '</p>';
  $output .= '<p>La resta entre ' . $x . ' y ' . $y . ' es: ' . ($x - $y) . '</p>';
  $output .= '<p>La mutiplicación entre ' . $x . ' y ' . $y . ' es: ' . ($x * $y) . '</p>';
  $output .= '<p>La división entre ' . $x . ' y ' . $y . ' es: ' . ($x / $y) . '</p>';
  $output .= '<p>El resto de la división entre ' . $x . ' y ' . $y . ' es: ' . ($x % $y) . '</p>';
  return $output;
}

/**
* Page callback url5
* Función que se invocará al cargar la página 
* www.example.com/admin/config/development/url5
*/
function menu_forcontu_menu1() {
  $output = t('Elemento de menú creado en el ejercicio 46.1');
  return $output;
}

/**
* Page callback - Tab 1
*/
function menu_forcontu_tab1() {
  $output = t('First tab');
  return $output;
}

/**
* Page callback - Tab 2
*/
function menu_forcontu_tab2() {
  $output = t('Second tab');
  return $output;
}

/**
* Page callback - Tab 3
*/
function menu_forcontu_tab3() {
  $output = t('Thrid tab');
  return $output;
}